<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZDAvhaH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZDAvhaH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZDAvhaH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZDAvhaH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZDAvhaH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZDAvhaH',
    'container.build_id' => '309f592c',
    'container.build_time' => 1536685511,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZDAvhaH');
